name: atelier
description: "Atelier is a peer-to-peer social marketplace."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase & State Management
  supabase_flutter: ^2.5.2
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0

  # UI & UX
  google_fonts: ^6.2.1 # For beautiful, custom fonts
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1 # Efficiently load and cache network images
  
  # Utility
  intl: ^0.19.0 # For date, time, and number formatting
  image_picker: ^1.1.2 # For picking images/videos from camera/gallery
  uuid: ^4.4.0 # For generating unique IDs on the client side

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  glassmorphism: ^3.0.0 # Add this line
  dotted_border: ^2.1.0
  

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  assets:
    - .env
    - assets/noise.png # 

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700